PROJECT_NAME = "PROJECT_NAME"
WEB_PORT = "WEB_PORT"
DB_PORT = "DB_PORT"
PMA_PORT = "PMA_PORT"

MAIN_DIR = "dampp-projects"
PUBLIC_DIR = "public"

ENVFILE_NAME = ".env"
DOCKERFILE_NAME = "Dockerfile"
DOCKERCOMPOSE_NAME = "docker-compose.yml"
PHPFILE_NAME = "index.php"

DOCKERCOMPOSE = """
# Auto generated by DAMPP.
# Do not remove.

version: '3.3'

services:

  web:
    build:
      context: ./public
      dockerfile: ../Dockerfile
    container_name: dmp-php-${PROJECT_NAME}
    image: php:8.1.1-apache
    depends_on:
      - db
    volumes:
      - ./public:/var/www/html
    ports:
      - ${WEB_PORT}:80

  db:
    container_name: dampp-mysql-${PROJECT_NAME}
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${DB_PORT}:6033

  phpmyadmin:
    container_name: dampp-pma-${PROJECT_NAME}
    image: phpmyadmin:latest
    depends_on:
      - db
    restart: always
    environment:
      PMA_ARBITRARY: 1
    ports:
      - ${PMA_PORT}:80
"""

DOCKERFILE = """
# Auto generated by DAMPP.
# Do not remove.

FROM php:8.1.1-apache
RUN apt-get update && apt-get upgrade -y
RUN docker-php-ext-install mysqli
EXPOSE 80
"""

PHP_FILE = """
<!DOCTYPE html>
<html lang=en>
<title>DAMP</title>
<meta charset=utf-8>
<meta content='width = device-width, initial-scale = 1, shrink-to-fit = no' name=viewport>
<style>
body {
    font-family: Ubuntu, sans-serif
}

div {
    padding: .5rem
}

a {
    text-decoration: none
}

code {
    color: #ff1493;
    font-weight: 700
}

.center {
    background-color: #fff;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, .2);
    transition: .3s;
    border-radius: 12.5px;
    padding: 2rem;
    margin: 0;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    text-align: center
}

.center:hover {
    box-shadow: 0 8px 16px 0 rgba(0, 0, 0, .2)
}

.btn {
    padding: 10px 35.5px 10px 35.5px;
    margin-top: 15px;
    color: #fff;
    background-color: #dc143c;
    border: 0;
    border-radius: 30px;
    font-size: 2.4vh;
    font-weight: 700
}

.btn:hover {
    background-color: #000;
    color: #fff;
    font-weight: 700
}

.tracking-in-contract {
    -webkit-animation: tracking-in-contract .8s cubic-bezier(.215, .61, .355, 1) both;
    animation: tracking-in-contract .8s cubic-bezier(.215, .61, .355, 1) both
}

@-webkit-keyframes tracking-in-contract {
    0% {
        letter-spacing: 1em;
        opacity: 0
    }

    40% {
        opacity: .6
    }

    100% {
        letter-spacing: normal;
        opacity: 1
    }
}

@keframes tracking-in-contract {
    0% {
        letter-spacing: 1em;
        opacity: 0
    }

    40% {
        opacity: .6
    }

    100% {
        letter-spacing: normal;
        opacity: 1
    }
}
</style>
<div class=center> <span class=tracking-in-contract> <a href=https://github.com/s3h4n/dampp.git target=_blank>
            <h1 style=color:#dc143c>DAMP</h1>
        </a>
        <h3>Dockerized Apache MySQL PHP</h3>
    </span>
    <hr>
    <div>
        <p>Customize <code>my-app/web/index.php</code> to see the changes.</p>
    </div>
    <hr>
    <div> <button class=btn onclick=open_php_my_admin() type=button>PhpMyAdmin</button> </div>
</div>
<script defer>
const open_php_my_admin = () => {
    window.open('http://localhost:8001/', '_blank');;
};
</script>
</body>

</html>
"""
